name: Snake animation

# Executa no push para o branch main ou manualmente
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run GitHub Readme Snake
        uses: GitHubDaily/gh-readme-snake-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          color: 'blue'   # você pode mudar a cor da cobrinha
