name: Github Snake animation

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate contribution snake
        uses: platane/snk@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

Add GitHub Snake workflow
